### ISSUE TITLE
Yarn support todo

### ISSUE THREAD

**Issue by tailhook** [tailhook/vagga#415]
* [ ] when `node_modules` are present in directory, yarn uses it instead of `--modules-folder` (warn?/create a signature file?)
* [ ] `YarnInstall` which does `yarn global add` (?)
* [ ] how to do `yarn add`? Docs are enough?
